"""Updated role schema with fixed permissions

Revision ID: 986f3ff85167
Revises: 98c283862a06
Create Date: 2025-03-24 05:16:43.301538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986f3ff85167'
down_revision = '98c283862a06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
