"""add appproved column

Revision ID: e7a75630a5fb
Revises: fc1ad6c1066c
Create Date: 2025-03-24 08:06:48.914796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a75630a5fb'
down_revision = 'fc1ad6c1066c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'approved')
    # ### end Alembic commands ###
