"""Simplified

Revision ID: fc1ad6c1066c
Revises: 986f3ff85167
Create Date: 2025-03-24 05:20:51.002736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1ad6c1066c'
down_revision = '986f3ff85167'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
