"""Users and Roles Table

Revision ID: fd628fcbabe7
Revises: 5c52837568a6
Create Date: 2025-03-25 03:39:52.461323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd628fcbabe7'
down_revision = '5c52837568a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthdate', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birthdate')
    # ### end Alembic commands ###
